---
title: "02_data"
author: "Bruce Wang"
date: "10/10/2019"
output: html_document
---

# Group Statistics
```{r}
df6 %>% group_by(BinStartTime) %>% tally()
df6 %>% group_by(SignalID) %>% tally()
df6 %>% group_by(ApproachId) %>% tally()
df6 %>% group_by(ArrivalsOnGreen) %>% tally()
df6 %>% group_by(ArrivalsOnRed) %>% tally()
df6 %>% group_by(ArrivalsOnYellow) %>% tally()
df6 %>% group_by(TotalVolume) %>% tally()
df6 %>% group_by(PlatoonRatio) %>% tally()
df6 %>% group_by(PercentGreen) %>% tally()
df6 %>% group_by(TotalTime) %>% tally()
df6 %>% group_by(TotalGreenTime) %>% tally()
df6 %>% group_by(TotalYellowTime) %>% tally()
df6 %>% group_by(TotalRedTime) %>% tally()
df6 %>% group_by(SplitFailures) %>% tally()
df6 %>% group_by(PhaseNumber) %>% tally()
df6 %>% group_by(GapOuts) %>% tally()
df6 %>% group_by(ForceOffs) %>% tally()
df6 %>% group_by(MaxOuts) %>% tally()
df6 %>% group_by(SevereRedLightViolations) %>% tally()
df6 %>% group_by(TotalRedLightViolations) %>% tally()
df6 %>% group_by(TotalCycles) %>% tally()
df6 %>% group_by(VCRatio) %>% tally()

ForceOffs <- table(df6$ForceOffs)
SplitFailures <- table(df6$SplitFailures)
ForceOffs <- table(df6$ForceOffs)
ForceOffs <- table(df6$ForceOffs)
ForceOffs <- table(df6$ForceOffs)
summary(ForceOffs)
summary(SplitFailures)
fivenum(ForceOffs)

```

# Plots
```{r}
ggplot(df6, aes(x = ForceOffs)) + geom_histogram(color = "black", fill = "Blue") 
ggplot(df6, aes(x = ForceOffs, fill = SignalID)) + geom_bar(color = "black", fill = "Blue") + facet_wrap(~SignalID)
# ggplot(df5, aes(x = ForceOffs)) + geom_histogram(aes(y = ..density..), color = "black", fill = "Blue") + geom_density(alpha = 0.2, fill = "#F60404")

ggplot(df6, aes(x = GapOuts)) + geom_histogram(color = "black", fill = "Blue") + scale_x_continuous(limits = c(-1, 20))
ggplot(df6, aes(x = GapOuts)) + geom_histogram(color = "black", fill = "Blue") + scale_x_continuous(limits = c(0, 20)) + scale_y_continuous(limits = c(0, 500))

ggplot(df6, aes(x = ArrivalsOnGreen)) + geom_histogram(color = "black", fill = "Green") 
ggplot(df6, aes(x = ArrivalsOnGreen, fill = SignalID)) + geom_bar(color = "Green", fill = "Green") + facet_wrap(~SignalID) + scale_x_continuous(limits = c(0, 200)) + scale_y_continuous(limits = c(0, 50))

ggplot(df6, aes(x = ArrivalsOnRed)) + geom_histogram(color = "black", fill = "Red")
ggplot(df6, aes(x = ArrivalsOnRed, fill = SignalID)) + geom_bar(color = "Red", fill = "Red") + facet_wrap(~SignalID) + scale_x_continuous(limits = c(0, 100)) + scale_y_continuous(limits = c(0, 400))

ggplot(df6, aes(x = PlatoonRatio)) + geom_histogram(color = "black", fill = "Blue")
ggplot(df6, aes(x = PlatoonRatio, fill = SignalID)) + geom_bar(color = "black", fill = "Blue") + facet_wrap(~SignalID)

ggplot(df6, aes(x = SplitFailures)) + geom_histogram(color = "black", fill = "Blue")
ggplot(df6, aes(x = SplitFailures, fill = SignalID)) + geom_bar(color = "black", fill = "Blue") + facet_wrap(~SignalID)

ggplot(df6, aes(x = TotalRedLightViolations)) + geom_histogram(color = "black", fill = "red")
ggplot(df6, aes(x = TotalRedLightViolations, fill = SignalID)) + geom_bar(color = "black", fill = "Red") + facet_wrap(~SignalID) + scale_x_continuous(limits = c(0, 40)) + scale_y_continuous(limits = c(0, 220))

ggplot(df6, aes(x = ArrivalsOnGreen, y = PlatoonRatio, color = SplitFailures)) +
  geom_point(alpha = 0.3) +
  #  facet_grid(is_protected~splitfails)
  facet_wrap(~SplitFailures) +
  scale_x_continuous(limits = c(0, 200))

# ggplot(df5, aes(x = ArrivalsOnGreen, y = PlatoonRatio, color = ForceOffs)) +
#   geom_point(alpha = 0.3) +
#   #  facet_grid(is_protected~splitfails)
#   facet_wrap(~SplitFailures) +
#   scale_x_continuous(limits = c(0, 200))

ggplot(df6, aes(x = ArrivalsOnRed, y = PlatoonRatio, color = SplitFailures)) +
  geom_point(alpha = 0.3) +
  #  facet_grid(is_protected~splitfails)
  facet_wrap(~SplitFailures) +
  scale_x_continuous(limits = c(0, 200))

# ggplot(df5, aes(x = ArrivalsOnGreen, y = PlatoonRatio, color = GapOuts)) +
#   geom_point(alpha = 0.3) +
#   #  facet_grid(is_protected~splitfails)
#   facet_wrap(~SplitFailures) +
#   scale_x_continuous(limits = c(0, 200))

ggplot(df6, aes(x = PercentGreen, y = PlatoonRatio, color = SplitFailures)) +
  geom_point(alpha = 0.2) + facet_wrap(~SplitFailures) 

ggplot(df6, aes(x = GapOuts, y = PlatoonRatio, color = SplitFailures)) +
  geom_point(alpha = 0.2) + facet_wrap(~SplitFailures)

ggplot(df6, aes(x = ForceOffs, y = PlatoonRatio, color = SplitFailures)) +
  geom_point(alpha = 0.2) + facet_wrap(~SplitFailures)

ggplot(df6, aes(x = SplitFailures, y = PlatoonRatio)) +
  geom_point() 
# facet_wrap(~SplitFailures)
# ggplot(df4, aes(x = SplitFailures, fill = ForceOffs)) +
#   geom_bar() +
#   facet_wrap(~ForceOffs)
# 
# ggplot(df4, aes(x = GapOuts, fill = SplitFailures)) +
#   geom_bar() +
#   facet_wrap(~SplitFailures)
# 
# ggplot(df4, aes(x = SplitFailures, fill = GapOuts)) +
#   geom_bar() +
#   facet_wrap(~GapOuts)
#   geom_point(alpha = 0.2) + scale_x_continuous(limits = c(0,4))

ggplot(df6, aes(x = PlatoonRatio, y = VCRatio, SignalID)) +
  geom_point(alpha = 0.2) + scale_x_continuous(limits = c(0,4))

ggplot(df6, aes(x = PlatoonRatio, y = VCRatio, SignalID)) +
  geom_point(alpha = 0.2) + scale_x_continuous(limits = c(0,4)) +
  facet_wrap(~SignalID)
# + scale_y_continuous(limits = c(0, 170))

# ggplot(df5, aes(x = ArrivalsOnGreen, fill = SignalID)) +
#   geom_bar() +
#   facet_wrap(~SignalID) + scale_x_continuous(limits = c(0, 200)) + scale_y_continuous(limits = c(0, 170))
# 
# ggplot(df5, aes(x = SplitFailures, fill = SignalID)) +
#   geom_bar() +
#   facet_wrap(~SignalID)

# ggplot(df5, aes(x = SplitFailures)) +
#   geom_bar() +
#   geom_abline(slope = 0, intercept = 3000, color = "red")
#   # facet_wrap(~ApproachId)
# 
# ggplot(df5, aes(x = ArrivalsOnGreen, fill = SignalID)) +
#   geom_bar() +
#   facet_wrap(~SignalID) +
#   scale_x_continuous(limits = c(0, 200)) + scale_y_continuous(limits = c(0, 170))

# ggplot(df5 %>% filter(),
#        aes(x = BinStartTime, y = SplitFailures, group = paste(SignalID, ApproachId))) +
#   geom_line()
# 
# ggplot(df5 %>% filter(),
#        aes(x = BinStartTime, fill = SplitFailures)) +
#   geom_bar()

ggplot(RA,aes(x = TotalRedLightViolations, fill = ApproachId)) +
  geom_bar() +
  facet_wrap(~ApproachId)

ggplot(df6,aes(x = TotalVolume, y = TotalRedLightViolations)) +
  geom_point(alpha = 0.2) +
  scale_x_continuous(limits = c(0,1100))

ggplot(df6,aes(x = TotalVolume, y = TotalRedLightViolations)) +
  geom_point(alpha = 0.2) +
  scale_x_continuous(limits = c(0,1100)) +
  facet_wrap(~SignalID)

## thresholed plots ========
ggplot(df6, aes(x = TotalVolume, y = ForceOffs)) +
  geom_abline(slope = 30/200, intercept = 0, col = "red")+
  geom_abline(slope = 30/400, intercept = -5, col = "red")+
  geom_abline(slope = 30/600, intercept = -10, col = "red")+
  geom_abline(slope = 30/800, intercept = -15, col = "red")+
  geom_hline(yintercept = 0.5, col = "blue")+
  geom_point(alpha = 0.2) 
  

# ggplot(df6, aes(x = TotalVolume, y = ForceOffs)) +
#   geom_vline(xintercept = 200, col = "red")+
#   geom_hline(yintercept = 15, col = "blue")+
#   geom_point(alpha = 0.2) + 
#   geom_smooth(method = 'lm')

ggplot(df6, aes(x = TotalVolume, y = GapOuts)) +
  geom_abline(slope = 30/200, intercept = 0, col = "red")+
  geom_abline(slope = 30/400, intercept = -5, col = "red")+
  geom_abline(slope = 30/600, intercept = -10, col = "red")+
  geom_abline(slope = 30/800, intercept = -15, col = "red")+
  geom_hline(yintercept = 0.5, col = "blue")+
  geom_point(alpha = 0.2)

ggplot(df6, aes(x = TotalVolume, y = ArrivalsOnGreen)) +
  geom_point(alpha = 0.2)

ggplot(df6, aes(x = TotalVolume, y = ArrivalsOnRed)) +
  geom_point(alpha = 0.2)

ggplot(df6, aes(x = PlatoonRatio, y = VCRatio)) +
  geom_point(alpha = 0.2)

ggplot(df6, aes(x = TotalVolume, y = SplitFailures)) +
  geom_point(alpha = 0.2)

ggplot(df6, aes(x = TotalVolume, y = TotalRedLightViolations)) +
  geom_point(alpha = 0.2)
```