---
title: "08_data"
author: "Bruce Wang"
date: "11/13/2019"
output: html_document
---


## Creating an Analysis Dataset
This scripte is to analyze the group of signals on StateSt corridor 
There are total ten signals included on the StateSt corrdior
```{r measures Dataset}
# Safety aggregation table: Red Light Actuation
RA <-read_xls("data/800N/800N_RedActuation.xls") %>%
  mutate(
    BinStartTime = as_datetime(BinStartTime)
  )

# Purdue Coordination Diagram aggregation table: Arrival On Green, Arrival On Red, and Platoon Ratio
PCD <-read_xls("data/800N/800N_PCD.xls") %>% 
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    PlatoonRatio = as.numeric(PlatoonRatio)
  )
    
# Split Failure aggregation table: Split Failures
SF <-read_xls("data/800N/800N_SplitFail.xls") %>% 
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    # SignalID = as.numeric(SignalID)
  )  

# Purdue Phase Termination Diagram aggregation table: Max out, Gap out, and Force Off
PPT <-read_xls("data/800N/800N_PPT.xls") %>% 
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalId = as.numeric(SignalId)
  )

# Number of Cycles for 800N: Cycles Number 
Cyc <-read_xls("data/800N/800N_Cycles.xls") %>%
  mutate(
    BinStartTime = as_datetime(BinStartTime)
  )

# Lane Configuration for 800N: Lane Configuration
LC <-read_xls("data/800N/800N_LaneConfig.xls") %>%
  distinct(ApproachID, LaneNumber, Abbreviation) %>%
  group_by(ApproachID, Abbreviation) %>%
  summarise(n = max(LaneNumber)) %>%
  filter(Abbreviation %in% c("T", "TR", "TL")) %>%
  summarise(
    n = sum(n)
  )
  
```

## Joining Aggregation Tables
```{r combine dataset}
# Create a Base Table: BinStartTime, SignalID, and ApproachID
BaseTable <-read_xls("data/800N/800N_BaseTable.xls") %>%
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalID = as.numeric(SignalID),
    ApproachId = as.numeric(ApproachId),
    year = lubridate::year(BinStartTime)
  ) %>% filter(year == 2018)

# Join all the aggregation tables into a signle analysis dataset
df <- left_join(
  BaseTable, PCD %>% select(-IsProtectedPhase),
  by = c("BinStartTime","ApproachId"))

df2 <- left_join(
  df, SF %>% select(-IsProtectedPhase),
  by = c("BinStartTime", "ApproachId"))

df3 <- left_join(
  df2, PPT, 
  by = c("BinStartTime", "SignalID" = "SignalId"))

df4 <- left_join(
  df3, RA,
  by = c("BinStartTime", "ApproachId")
)

df5 <- left_join(
  df4, Cyc,
  by = c("BinStartTime", "ApproachId")
)

df6 <- left_join(
  df5, LC,
  by = c("ApproachId" = "ApproachID")
)

df7 <- df6 %>% select(-year) %>% select(-Id) %>% select(-Volume) %>%
  mutate(
    TotalVolume = as.numeric(TotalVolume),
    PercentGreen = as.numeric(PercentGreen),
    TotalTime = as.numeric(TotalTime),
    TotalGreenTime = as.numeric(TotalGreenTime),
    TotalYellowTime = as.numeric(TotalYellowTime),
    TotalRedTime = as.numeric(TotalRedTime),
  )  %>% 
  mutate(
    saturation = 1969 * n, #vph
    sat_in_period = saturation * (TotalTime) / (60 * 60), # vph * s in period / s in hour = vp period
    percent_green = TotalGreenTime / TotalTime, #unitless
    VCRatio = TotalVolume / (sat_in_period * percent_green) # vpp / (max vpp * percent green)
  )  %>%
  mutate(
    # Y_M_D = as.Date(df7$BinStartTime),
    # H_M_S = format(as.POSIXct(df7$BinStartTime) ,format = "%H:%M:%S"),
    # AMPeak = subset(df7, H_M_S > "7:00:00 " & H_M_S < "8:45:00")
    AMPeak = hour(BinStartTime) >= 7 & hour(BinStartTime) <= 8
    # AMPeak = hour(BinStartTime) %in% c("07:00:00", "07:15:00")
  )  %>%
  mutate(
    # ForceOffsPerCycle = ForceOffs / TotalCycles,
    # GapoutsPerCycle = GapOuts / TotalCycles,
    PercentAOG = (ArrivalsOnGreen + ArrivalsOnYellow) / TotalVolume,
    PercentAOR = ArrivalsOnRed / TotalVolume,
    SplitFailuresPerCycle = SplitFailures / TotalCycles,
    TotalRedLightViolationsPerCycle = TotalRedLightViolations / TotalCycles
  )

dfAMPeck <- df7 %>% filter(df7$AMPeak == "TRUE")

dfMidDay <- df7 %>% filter(df7$AMPeak == "FALSE")
```