---
title: "Aggregation Data-800N"
author: "Bruce Wang"
date: "11/15/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Loading Libraries
```{r Loading Libraries}
## Load Libraries
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
```

## Creating an Analysis Dataset
This scripte is to analyze the group of signals on 800N corridor 
There are total 5 signals and 10 approaches included on the 800N corrdior
```{r Signal Performance Measures Dataset}
# Safety aggregation table: Red Light Actuation
RA_800N <-read_xls("data/800N/800N_RedActuation.xls") %>%
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalId = as.numeric(SignalId)
  )

# Purdue Coordination Diagram aggregation table: ArrivalOnGreen, ArrivalOnRed, and Platoon Ratio
PCD_800N <-read_xls("data/800N/800N_PCD.xls") %>% 
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalId = as.numeric(SignalId),
    TotalVolume = as.numeric(TotalVolume),
    PlatoonRatio = as.numeric(PlatoonRatio)
  )
    
# Split Failure aggregation table: Split Failures
SF_800N <-read_xls("data/800N/800N_SplitFail.xls") %>% 
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalId = as.numeric(SignalId)
  )  

# Purdue Phase Termination Diagram aggregation table: Max out, Gap out, and Force Off
PPT_800N <-read_xls("data/800N/800N_PPT.xls") %>% 
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalId = as.numeric(SignalId)
  )

# Number of Cycles for 800N: Cycles Number 
Cyc_800N <-read_xls("data/800N/800N_Cycles.xls") %>%
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalId = as.numeric(SignalId)
  )

```

## Combine Aggregation Tables using Left Join command
```{r Combine Dataset}
# Create a Base Table: BinStartTime, SignalID, and ApproachID
BaseTable_800N <-read_xls("data/800N/800N_BaseTable.xls") %>%
  mutate(
    BinStartTime = as_datetime(BinStartTime),
    SignalId = as.numeric(SignalId),
    ApproachId = as.numeric(ApproachId),
  )

# Join all the aggregation tables into a signle analysis dataset
df1_800N <- left_join(
  BaseTable_800N, PCD_800N %>% select(-IsProtectedPhase),
  by = c("BinStartTime", "SignalId", "ApproachId"))

df2_800N <- left_join(
  df1_800N, SF_800N %>% select(-IsProtectedPhase),
  by = c("BinStartTime", "SignalId", "ApproachId"))

df3_800N <- left_join(
  df2_800N, PPT_800N, 
  by = c("BinStartTime", "SignalId", "ApproachId"))

df4_800N <- left_join(
  df3_800N, RA_800N %>% select(-IsProtectedPhase),
  by = c("BinStartTime", "SignalId", "ApproachId"))

df5_800N <- left_join(
  df4_800N, Cyc_800N,
  by = c("BinStartTime", "SignalId", "ApproachId"))

df6_800N <- df5_800N %>% 
  mutate(
    TotalTime = as.numeric(TotalTime),
    TotalGreenTime = as.numeric(TotalGreenTime),
    TotalYellowTime = as.numeric(TotalYellowTime),
    TotalRedTime = as.numeric(TotalRedTime),
    PercentGreen = as.numeric(PercentGreen)
  ) %>%
  mutate(
    AMPeak = hour(BinStartTime) >= 7 & hour(BinStartTime) <= 8
  )  %>%
  mutate(
    PercentAOG = (ArrivalsOnGreen + ArrivalsOnYellow) / TotalVolume,
    PercentAOR = ArrivalsOnRed / TotalVolume,
    SFPerCycle = SplitFailures / TotalCycles,
    RAPerCycle = TotalRedLightViolations / TotalCycles
  )

dfAMPeak_800N <- df6_800N %>% 
  filter(df6_800N$AMPeak == "TRUE") %>% 
  write_rds("data/dfAMPeck.rds")

dfMidDay_800N <- df6_800N %>%
  filter(df6_800N$AMPeak == "FALSE") %>% 
  write_rds("data/dfMidDay.rds")
```
