---
title: "Dataset-Combined"
author: "Bruce Wang"
date: "11/21/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

### combine all the dataset with NA Value
```{r}
dfAMPeak_FtUnion <- read_rds("data/dfAMPeak_FtUnion.rds") %>% mutate(Corrdior = "FtUnion")
dfMidDay_FtUnion <- read_rds("data/dfMidDay_FtUnion.rds") %>% mutate(Corrdior = "FtUnion")
dfAMPeak_800N <- read_rds("data/dfAMPeak_800N.rds") %>% mutate(Corrdior = "800N")
dfMidDay_800N <- read_rds("data/dfMidDay_800N.rds") %>% mutate(Corrdior = "800N")
dfAMPeak_StateSt <- read_rds("data/dfAMPeak_StateSt.rds") %>% mutate(Corrdior = "StateSt")
dfMidDay_StateSt <- read_rds("data/dfMidDay_StateSt.rds") %>% mutate(Corrdior = "StateSt")

dfCorridors_NA <- rbind(dfAMPeak_FtUnion, dfAMPeak_800N, dfAMPeak_StateSt, dfMidDay_FtUnion, dfMidDay_800N, dfMidDay_StateSt) %>%
  write_rds("data/dfCorridors_NA.rds")
```

### combine all the na.omit dataset
```{r}
clustered_dfAMPeak_FtUnion <- read_rds("data/clustered_dfAMPeak_FtUnion.rds") %>% mutate(Corrdior = "FtUnion")
clustered_dfMidDay_FtUnion <- read_rds("data/clustered_dfMidDay_FtUnion.rds") %>% mutate(Corrdior = "FtUnion")
clustered_dfAMPeak_800N <- read_rds("data/clustered_dfAMPeak_800N.rds") %>% mutate(Corrdior = "800N")
clustered_dfMidDay_800N <- read_rds("data/clustered_dfMidDay_800N.rds") %>% mutate(Corrdior = "800N")
clustered_dfAMPeak_StateSt <- read_rds("data/clustered_dfAMPeak_StateSt.rds") %>% mutate(Corrdior = "StateSt")
clustered_dfMidDay_StateSt <- read_rds("data/clustered_dfMidDay_StateSt.rds") %>% mutate(Corrdior = "StateSt")

dfCorridors <- rbind(clustered_dfAMPeak_FtUnion, clustered_dfAMPeak_800N, clustered_dfAMPeak_StateSt, clustered_dfMidDay_FtUnion, clustered_dfMidDay_800N, clustered_dfMidDay_StateSt) %>%
  write_rds("data/dfCorridors.rds")
```

