---
title: "Evaluating the Quality of Signal Operations using Signal Performance Measures"
editor_options: 
  chunk_output_type: console
---

### This wedsite is to introduce the steps of ATSPMs data analysis and evaluation  

More about ATSPM: "ATSPMs use detector data to show actual and historical performance of signalized intersections. They use high-resolution data capability added to existing infrastructure to evaluate the quality of progression of traffic along a corridor. In Utah, the measured data alert UDOT of detector malfunctions and provide insight into vehicle delay from volume, speed, and travel time detection. UDOT uses the data to optimize mobility and manage traffic signal timing and maintenance to reduce congestion, save fuel costs, and improve safety (UDOT, 2019b)."

The purpose of this research is to evaluate the real-time data collected through the ATSPM database and determine which performance measures can be used for evaluation and to then identify thresholds for each performance measure chosen. The following webpages explain the source of data used, the performance measures chosen, and the evaluation methods picked. 


